version: '3.8'

services:
  monitoring:
    build: .
    container_name: monitoring_app
    ports:
      - "1111:5000"
    volumes:
      # mount فایل دیتابیس
      - ./monitoring_master.db:/app/monitoring_master.db
      # mount پوشه دیتا
      - ./data:/data
      # mount کل پروژه (برای توسعه)
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Tehran
    restart: unless-stopped