[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid
user=root

[program:web_master]
command=python /app/web_master.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:agent]
command=python /app/agent_local.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0